version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /var/datafile2:/mnt:z
      - /var/share:/mnt2:z
    command: '-s "share;/mnt" -s "bob;/mnt2;yes;no;no;bob" -u "bob;bobspasswd"'

networks:
  default:
